### ISSUE TITLE
`SENDING TO` unending loop

### ISSUE THREAD

**Issue by irriden** [stakwork/sphinx-key#90]
In case broker sends a message, and signer crashes before returning a response, signer will reconnect with broker under a new client id, but broker is currently stuck in an unending loop sending that same message to the previous client id.

**Comment by Evanfeenstra** [comment]
ok so we need to choose a number of retries the broker will do before giving up on a client and trying a new one. 3 times? 10 times?

**Comment by Evanfeenstra** [comment]
Here new clients are added to the beginning of the `clients` array, so the next try around, the broker should be trying to newest client https://github.com/stakwork/sphinx-key/blob/master/broker/src/conn.rs#L25

Are you sure you saw this on latest broker? and that the new client connected fine?

**Comment by Evanfeenstra** [comment]
fixed in master (control messages fail right away)
